[package]
name = "bafiq"
description = "BAM Flag Index Query tool"
version = "0.0.5"
edition = "2021"

[dependencies]
rust-htslib = "0.49.0"
clap = { version = "*", features = ["derive"] }
anyhow = "1.0"       # optional, for nicer error handling
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
flate2 = "*"
libdeflater = "1.23.0"
memmap2 = "0.9.5"

# [profile.release]
# debug = true
